[phases.setup]
nixPkgs = [
  "...",
        "nodejs",  
    "python39", 
    "ffmpeg",   
    "autoconf", 
    "automake",  
    "gcc",      
    "make",     
    "gawk"      
]

[build]
builder = "node"