[phases.setup]
nixPkgs = [
  "...",
    "nodejs",  
    "ffmpeg",
    "python39",
    "autoconf",
    "automake", 
    "gcc",      
    "make",     
    "gcompat",  
    "gawk",     
]

[build]
builder = "node"